# -*- coding: utf-8 -*-
"""Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1upLC5euBWTrLE7HVZH7RAujexp77TYRQ
"""

# model.py — Transformer model + predict function
try:
    import torch  # type: ignore[reportMissingImports]
    import torch.nn as nn  # type: ignore[reportMissingImports]
except Exception as e:
    torch = None
    nn = None
    _torch_import_error = ImportError(
        "PyTorch is required to run this module. Please install it (e.g. `pip install torch`)\n"
        f"Original error: {e}")
else:
    _torch_import_error = None

import numpy as np

# ── Model Architecture ──────────────────────────
if torch is not None and nn is not None:
    class LogTransformer(nn.Module):
        def __init__(self, input_dim=1, d_model=32, nhead=4,
                     num_layers=2, max_len=50, dropout=0.3):
            super().__init__()
            self.input_proj = nn.Linear(input_dim, d_model)
            pe = torch.zeros(max_len, d_model)
            pos = torch.arange(0, max_len).unsqueeze(1).float()
            div = torch.exp(torch.arange(0, d_model, 2).float() *
                            -(torch.log(torch.tensor(10000.0)) / d_model))
            pe[:, 0::2] = torch.sin(pos * div)
            pe[:, 1::2] = torch.cos(pos * div)
            self.register_buffer('pe', pe.unsqueeze(0))
            encoder_layer = nn.TransformerEncoderLayer(
                d_model=d_model, nhead=nhead,
                dim_feedforward=128, dropout=dropout, batch_first=True)
            self.transformer = nn.TransformerEncoder(
                encoder_layer, num_layers=num_layers)
            self.classifier = nn.Sequential(
                nn.Linear(d_model, 16), nn.ReLU(),
                nn.Dropout(dropout), nn.Linear(16, 1), nn.Sigmoid())

        def forward(self, x):
            x = self.input_proj(x)
            x = x + self.pe
            x = self.transformer(x)
            x = x.mean(dim=1)
            return self.classifier(x).squeeze(-1)
else:
    class LogTransformer:
        def __init__(self, *args, **kwargs):
            raise _torch_import_error

# ── Load Model Once ─────────────────────────────
device = torch.device('cpu') if torch is not None else None  # Streamlit cloud has no GPU, use CPU

_model = None  # global so it loads only once

def get_model(model_path="models/best_transformer.pt"):
    global _model
    if _model is None:
        _model = LogTransformer().to(device)
        _model.load_state_dict(
            torch.load(model_path, map_location=device))
        _model.eval()
    return _model

# ── Event Encoding Map ───────────────────────────
EVENT_TO_INT = {
    'E1':0,'E10':1,'E11':2,'E12':3,'E13':4,
    'E16':7,'E17':8,'E2':11,'E3':22,'E32':25,
    'E34':27,'E35':28,'E4':33,'E5':42,'E6':43,'E7':44
}
MAX_VAL = 44
MAX_LEN = 50

# ── Parse Raw Log Lines → EventSequence ─────────
import re

EVENT_PATTERNS = [
    (r'Receiving block',           'E1'),
    (r'PacketResponder.*terminat', 'E2'),
    (r'PIPELINE_SETUP',            'E3'),
    (r'writeBlock',                'E4'),
    (r'Received block',            'E5'),
    (r'block report',              'E6'),
    (r'heartbeat',                 'E7'),
    (r'block already exists',      'E10'),
    (r'IOException',               'E11'),
    (r'block.*not.*found',         'E12'),
    (r'Connection refused',        'E16'),
    (r'Replication.*failed',       'E17'),
    (r'corrupt',                   'E32'),
    (r'unresponsive',              'E35'),
]

def line_to_event(content):
    """Map one log line content → EventId"""
    content_lower = content.lower()
    for pattern, event_id in EVENT_PATTERNS:
        if re.search(pattern, content, re.IGNORECASE):
            return event_id
    return 'E1'  # default

def parse_log_file(log_text):
    """
    Input:  raw log file text (string)
    Output: dict of {block_id: [E1, E11, E2, ...]}
    """
    blocks = {}
    pattern = r'\d+\s+\d+\s+\d+\s+\w+\s+[\w.$]+:\s+(.*)'

    for line in log_text.strip().split('\n'):
        line = line.strip()
        if not line:
            continue
        match = re.match(pattern, line)
        if not match:
            continue
        content = match.group(1)
        
        # Extract block ID
        blk_match = re.search(r'(blk_[-]?\d+)', content)
        
        if blk_match:
            # If it's an HDFS log, use the Block ID
            block_id = blk_match.group(1)
        else:
            # 🛠️ THE FIX: If it's the E-Commerce log, group it by the component (e.g., auth.LoginService)
            component = line.split()[4].replace(':', '')
            block_id = f"ecommerce_{component}"
            
        event_id = line_to_event(content)
        if block_id not in blocks:
            blocks[block_id] = []
        blocks[block_id].append(event_id)

    return blocks

def predict_block(event_sequence_list):
    """
    Input:  [E1, E11, E11, E2] list
    Output: anomaly probability float
    """
    model = get_model()
    encoded    = [EVENT_TO_INT.get(e, 0) for e in event_sequence_list]
    normalized = [v / MAX_VAL for v in encoded]
    if len(normalized) < MAX_LEN:
        normalized += [0.0] * (MAX_LEN - len(normalized))
    normalized = normalized[:MAX_LEN]
    X = torch.FloatTensor(normalized).reshape(1, 50, 1).to(device)
    with torch.no_grad():
        prob = model(X).item()
    return round(prob, 4)